swagger: '2.0'
info:
  version: '1.0.0'
  title: Greeting API
  contact:
    name: Swagger API team
    email: foo@example.com
    url: http://swagger.io
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: localhost:8080
basePath: /
schemes:
  - http

paths:
  /greeting:
    get:
      description: |
        Mandatory query param of **client** determines
        the welcome message
      operationId: greeting
      produces:
        - text/plain  
      parameters:
        -
          name: client
          in: query
          description: Name of the client
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            type: string